"""empty message

Revision ID: 0f92b17f88fa
Revises: ee57b6ca22c4
Create Date: 2024-09-28 15:38:19.958195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f92b17f88fa'
down_revision = 'ee57b6ca22c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aeropuerto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aeropuerto', sa.String(length=60), nullable=False))
        batch_op.drop_column('eropuerto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aeropuerto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eropuerto', mysql.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('aeropuerto')

    # ### end Alembic commands ###
