"""empty message

Revision ID: 54506e9b6e21
Revises: 
Create Date: 2024-09-28 13:59:57.643881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54506e9b6e21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('idrol', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idrol')
    )
    op.create_table('usuario',
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nombres', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('clave', sa.String(length=250), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.idrol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idusuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('rol')
    # ### end Alembic commands ###
