"""empty message

Revision ID: ee57b6ca22c4
Revises: 54506e9b6e21
Create Date: 2024-09-28 15:23:37.667990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee57b6ca22c4'
down_revision = '54506e9b6e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('idpais', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idpais')
    )
    op.create_table('aeropuerto',
    sa.Column('idaeropuerto', sa.Integer(), nullable=False),
    sa.Column('eropuerto', sa.String(length=60), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('ciudad', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.idpais'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idaeropuerto')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pais', ['pais_id'], ['idpais'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pais_id')

    op.drop_table('aeropuerto')
    op.drop_table('pais')
    # ### end Alembic commands ###
